
apiVersion: camel.apache.org/v1alpha1
kind: EIP-BRANCH
metadata:
  name: circuit-breaker
  annotations:
    camel.apache.org/kamelet.icon: "data:image/gif;base64,R0lGODlhVgA2AKIAAP///8z/mYCAgAAAAP4BAgAAAAAAAAAAACH5BAQUAP8ALAAAAABWADYAAAP/OLrc/jDKSRm4oOrN+8PZEIxkaZ5oqq5sq4BKK890nSpCHtp875c4XexHLLKCgp1xyRwhlc3l4vccRosNX1V0JXq4pm3Xm+2Jx7zhVDvIJa1oGTwANreF9bhqLr2/83phgExngYJ6hYZ0g1eJiIxdjmN8j25Qk5BxkoSZlXiRnYGbVKGGozQxlHalN36XaWt9sTabX6xHHiinLmVGvbSuqjMMUbPAlsLDt6hkyMuKfc7Q04vS1Iq7103Z2tGf3Z5/4OGv48XBz+ao6OqY1u1Aybjv8IvG6/TtX7rs9U7EdvLBu4fvmz8nzQwexNJvIUOBDmE5s0WxYoeJFjNqfGAJKYObjyBDihxJsqTJkyJBoFzJsqXLlB5fypxJsyOImzhz6tzJs6fPnwkAADs="
    camel.apache.org/provider: "Kaoto Bridge"
    camel.apache.org/kamelet.group: "Knative"
    kaoto.io/minbranches: "2"
    kaoto.io/maxbranches: "2"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "Circuit Breaker."
    description: "The Circuit Breaker pattern is inspired by the real-world electrical circuit breaker, which is used to detect excessive current draw and fail fast to protect electrical equipment. The software-based circuit breaker works on the same notion, by encapsulating the operation and monitoring it for failures. The Circuit Breaker pattern operates in three states."
    required:
    properties:
      resilience4jConfiguration:
        title: Resilience 4J Configuration
        description: Configures the circuit breaker to use Resilience4j with the given configuration.
        type: object
      faultToleranceConfiguration:
        title: Fault Tolerance Configuration
        description: Configures the circuit breaker to use MicroProfile Fault Tolerance with the given configuration.
        type: object
      configuration:
        title: Configuration
        description: Refers to a circuit breaker configuration (such as resillience4j, or microprofile-fault-tolerance) to use for configuring the circuit breaker EIP.
        type: string
      description:
        title: Description
        description: Sets the description of this node.
        type: object
