
apiVersion: camel.apache.org/v1alpha1
kind: EIP
metadata:
  name: convert-body-to
  annotations:
    camel.apache.org/kamelet.icon: "data:image/gif+xml;base64,R0lGODlhVgA2AKIAAP///8z/mYCAgAAAAP4BAgAAAAAAAAAAACH5BAQUAP8ALAAAAABWADYAAAP/OLrc/jDKSRm4oOrN+8PZEIxkaZ5oqq5sq4BKK890nSpCHtp875c4XexHLLKCgp1xyRwhlc3o7zmUWm1U0cnzoHEd20EuWQWCzuh0xqtuo7VAsRBudtvXs8HdTnfKyX1Oe26BKnqDaoFZKIeIb2yOjyaLW5GSMo2WF4p/UHWam5CgeHFjniSZmoU3o6GTnWWoiAtnq4y1qXxhprGCgw0YtpWbFr+7c7eOwMKTIbTKx4DJkQ1exdTRp76qDEfXlpy8hbnU3WHPo+HIw+kB1X4L7q2kqLDj83ARsq3q0uygfd7ta/dK3DSA9bpsQ1hwXTN+7sxFjEcOWkN/D9NJjIOOrGEph5/AbWT0DdtFbfJExstT0tjJXilnWWBmBpjFjxhD8rlGc6DNPf1QVkzTkd4RXDfrGfynSpRHpSAHPj0K8eW9qpjwZYM51GVWrFBzSm2aR6vVg2S/EsQp1KzaqRGXvvqyEhPdumFRXtl7wx7fv97kAh7MFibhv5QOH06seHCWu5AjTxAnubLlJxjGaN7MubPnz6BDi+4MYrTp06hTk86surXr16bmyZ49KAEAOw=="
    camel.apache.org/provider: "Kaoto Bridge"
    camel.apache.org/kamelet.group: "Knative"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "Convert Body To"
    description: "The ConvertBodyTo EIP allows you to transform the message body to a different type."
    required:
      - type
    type: object
    properties:
      type:
        title: Type 
        description: "The java type to convert to."
        type: string
        example: 'java.lang.String'
      mandatory:
        title: "Is it mandatory?"
        description: "When mandatory then the conversion must return a value (cannot be null), if this is not possible then NoTypeConversionAvailableException is thrown. Setting this to false could mean conversion is not possible and the value is null."
        type: boolean
        default: true
      charset:
        title: Character Set
        description: "To use a specific charset when converting."
        type: string
        example: "UTF8"
      description:
        title: Marker
        description: "Sets the description of this node."
        type: string
