
apiVersion: camel.apache.org/v1alpha1
kind: EIP
metadata:
  name: delay
  annotations:
    camel.apache.org/kamelet.icon: "data:image/gif+xml;base64,R0lGODlhVgA2AMQAAAAAAP///4SEhJmZmTo6OikpKdfX11NTU76+vmxsbO/v70FBQa2trY2NjSIiIszMzObm5n19fTMzM0pKSllZWff3997e3pSUlMTExKamprW1tXJycmZmZgAAAAAAAAAAACH5BAAHAP8ALAAAAABWADYAAAX/YCCOZGmeaKqubOu+cCzPdG3feK7vfO//wBdgSCwaj8hisAbwNZezJw8QiQigMOmOWsUKndWI16XVccVjVjl3TqtPkAKD1nar1oFL4RqoxOp2KFIZCRkUEgQSFBcHaGRhgSlSGwUSEhMUB5YSG1mQkSdSGJYDCiIIEwUDnl2gJlIReyWjE6aPra4kTQYZCxIGJgkFHBC3jrkiTRIFiQ8mAhIOGsbIugEWGL7AJYer1NXJIwMFCX7iiiKGFiMXDOYjgNVSEL4JFhUKF5ZiCgQFiwigFUBQIh4yKQwqFVhwIJWlBdcW+Nq0gMA2eJ/ASTFQSMDECBgEaMiWaIJEXwQm/6zDiEveCQYSvEUYQKAmAwU4ITSwNOHBNoO58AQoFiBDpZoESwxAlJIgUFdCRyCQKGHOiQgSJgZ4CirqCA2XbJl4YEnAOq6RvIogO+FdCQWpMCTL6HJFhktuSVjwlxRtILWoal4sAVPChbktD64Q4CBRJxNwCUhssJWuYhUPNmyw1MAthARMKRTza0ftiM2KNDx4MGACKQtESbsxfbrmJqbeWB673MKoZIk1KbyyHPSFhgMcLOCExkcXcagwIIiFcCBv5cTFe8hOQ/vP8644kHxPG77g+L/lRzzYPqb7HfVndme38WR9GOzQbzSxf7+5vCQABnhfBBcQBY4IAyao4CKC9zWw0oEIMighgw0YCGEAAmSo4YYcdujhAA9eKOKIXoQAADs="
    camel.apache.org/provider: "Kaoto Bridge"
    camel.apache.org/kamelet.group: "Knative"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "Delay"
    description: "The Claim Check from the EIP patterns allows you to replace message content with a claim check (a unique key), which can be used to retrieve the message content at a later time."
    required:
      - expression
    type: object
    properties:
      expression:
        title: Expression 
        description: "Expression to define how long time to wait (in millis)."
        type: object
        example: '${body}'
      simple:
        title: "Simple Expression"
        description: "Expression to define how long time to wait (in millis)."
        type: string
      constant:
        title: "Constant Expression"
        description: "Expression to define how long time to wait (in millis)."
        type: string
      jq:
        title: "Jq Expression"
        description: "Expression to define how long time to wait (in millis)."
        type: string
      jsonpath:
        title: "JSON Path Expression"
        description: "Expression to define how long time to wait (in millis)."
        type: string
      asyncDelayed:
        title: Async Delayed
        description: "Enables asynchronous delay which means the thread will not block while delaying."
        type: boolean
      callerRunsWhenRejected:
        title: Caller Runs When Rejected
        description: "Whether or not the caller should run the task when it was rejected by the thread pool. Is by default true."
        type: boolean
      executorService:
        title: Executor Service
        description: "To use a custom Thread Pool if asyncDelay has been enabled."
        type: object
      description:
        title: Description
        description: "Sets the description of this node."
        type: object
