apiVersion: camel.apache.org/v1alpha1
kind: EIP-BRANCH
metadata:
  name: filter
  annotations:
    camel.apache.org/kamelet.icon: "data:image/svg+xml;base64,R0lGODlhVgA2ALMAAP///8z/mbKysq2traioqJmZmY2NjYGBgXR0dGZmZlhYWFJSUgAAAP4BAgAAAAAAACH5BAUUAA0ALAAAAABWADYAAAT/kMlJq704680p+EAnjmR5gSETrGzrvnAsz3QtoVKt73wfS4dgykcsGltAYe7IbNKSh6FzSl1BpdXs8brUen1cVdV0mYazDIUigTgYCgXCQEAfEAgFwwGRSIidZ2h9bW9xc3V3eXt9f02BY4NucHJ0AnZ4enyNjgxBUV2QhJOHlomZfmOdSptmbJKGlZeKCKxMj2iisIiYe7Vbqp++jrmUu4rCRrdor8WlvMhFymPMpLIG0NHAWF4Mhc3W2ETSY97VieHi2qDco7HnX+Nj7bvo6Z7b8HfmBPVg6v3R9LkD2CMergJ0CiBYQJCHwTEIEApQyPCLlX8WkURMuLDhjodUnhhsnNgxI0gzIyl61HESUMqSFlsOk6jSJMaMVl5WjHkTp0iaMOH1NKlzpY2hMYvavLcOnlKeTI1+fCo0Ks6cQHdWXXU1wE+OWrkhdZpV6gyZtjAs5dq1LZKxbn3CjQuVLd2uaO+mtar3ahgygAMDjiq4sOEN90B4Wsy4sePHkCNLnuwYBeXLmDNrrqx4s+fPoBOjGE26tOnTqFOrXh0BADs="
    camel.apache.org/provider: "Kaoto Bridge"
    camel.apache.org/kamelet.group: "Knative"
    kaoto.io/minbranches: "1"
    kaoto.io/maxbranches: "1"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "Filter"
    description: "The Message Filter from the EIP patterns allows you to filter messages. The message filter implemented in Camel is similar to if (predicate) { block } in Java. The filter will include the message if the predicate evaluated to true."
    properties:
      simple:
        description: Simple language content of the body to set.
        type: string
        example: 'Body: ${body}'
