apiVersion: camel.apache.org/v1alpha1
kind: EIP
metadata:
  name: remove-properties
  annotations:
    camel.apache.org/kamelet.icon: "data:image/gif;base64,R0lGODlhVgA2AKIAAP///8z/mYCAgAAAAP4BAgAAAAAAAAAAACH5BAQUAP8ALAAAAABWADYAAAP/OLrc/jDKSRm4oOrN+8PZEIxkaZ5oqq5sq4BKK890nSpCHtp875c4XexHLLKCgp1xyRwhlc3o7zmUWm1U0cnzoHEd20EuWQWCzuh0xqtuo7VAsRBudtvXs8HdTnfKyX1Oe26BKnqDaoFZKIeIb2yOjyaLW5GSMo2WF4p/UHWam5CgeHFjniSZmoU3o6GTnWWoiAtnq4y1qXxhprGCgw0YtpWbFr+7c7eOwMKTIbTKx4DJkQ1exdTRp76qDEfXlpy8hbnU3WHPo+HIw+kB1X4L7q2kqLDj83ARsq3q0uygfd7ta/dK3DSA9bpsQ1hwXTN+7sxFjEcOWkN/D9NJjIOOrGEph5/AbWT0DdtFbfJExstT0tjJXilnWWBmBpjFjxhD8rlGc6DNPf1QVkzTkd4RXDfrGfynSpRHpSAHPj0K8eW9qpjwZYM51GVWrFBzSm2aR6vVg2S/EsQp1KzaqRGXvvqyEhPdumFRXtl7wx7fv97kAh7MFibhv5QOH06seHCWu5AjTxAnubLlJxjGaN7MubPnz6BDi+4MYrTp06hTk86surXr16bmyZ49KAEAOw=="
    camel.apache.org/provider: "Kaoto Bridge"
    camel.apache.org/kamelet.group: "Knative"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "Remove Properties"
    description: "The Remove Properties EIP allows you to remove one or more Exchange properties, based on pattern syntax."
    required:
      - pattern
    properties:
      pattern:
        title: Pattern
        description: "Name or pattern of properties to remove. The pattern is matched in the following order: 1 = exact match 2 = wildcard (pattern ends with a and the name starts with the pattern) 3 = regular expression (all of above is case in-sensitive)."
        type: string
      excludePattern:
        title: Exclude Pattern
        description: "Name or patter of properties to not remove. The pattern is matched in the following order: 1 = exact match 2 = wildcard (pattern ends with a and the name starts with the pattern) 3 = regular expression (all of above is case in-sensitive)."
        type: string
      description:
        title: Description
        description: "Sets the description of this node."
        type: object
