apiVersion: camel.apache.org/v1alpha1
kind: EIP-BRANCH
metadata:
  name: saga
  annotations:
    camel.apache.org/kamelet.icon: "data:image/gif;base64,R0lGODlhVgA2AMQAAP///8z/md/f37nni8PDw6zXgbW1tZm/c4yvaZmZmYSEhHKPVmZ/TEBAQCYwHQAAAP4BAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAQUAP8ALAAAAABWADYAAAX/ICCO42OeaKqubOu+ZCzHZmDfeK7vfO/vJoOBMCuKar+kcvkzKZ7GIpJJrSad0Khsau3aCo5CFavQbh/eNNgkZpLNNHS663idGLk3vCSfUxF1JgsHhIWGbTd6ewBcfj+ADQUIDwtjD09li4x9jj2QiANWinuNnTifjqNwpaaonapmrH6uprBasl60pgG2UbhVn0+7iZdZRURxjq7Cw7zFmSLII0/Sm3O6zcSYJNTTmMi/OgUNDw4LDpFWYIhLo5gKCQnv1OE5gSYHPMw7aw/sVwwwxYs3r+ATcjkY2DmRb8c+Hfde4MHxzOATAQLmGbCGo4ChjwcihrIySRDIQ3kc/2DCiPGdCEwbj3BKUpJSmkmVqLh7ElNBTD5VPP7L8XDHSJ3PuP2UMrNT0VdJNdXL5qWXkalURUVdhJXK01RbSTV19NWPVaZZs52d0TVtu7Crxvop+yWMpW1S5c6h22+oj7Vn3O6I6GKiNmNiBeuoOegkoX+AkzWjGwDnXcRxs1EOcNQN3Fh6FV+GJpaB6dOoU6tezbq169WRSSycneIJ7duftTjY3aC379/AgwtvcHC48eO/8WoCYMCi8+fQo0tXrqn59OvYs1Nfzt1IRgUCuosfT976UvLo0xf5flG9+/cirPOET588+5X18y+XD1O/f02Y/SdgFAEOaGAMBR6oYAuCChrIYIMCPuhfCAA7"
    camel.apache.org/provider: "Kaoto Bridge"
    camel.apache.org/kamelet.group: "Knative"
    kaoto.io/minbranches: "1"
    kaoto.io/maxbranches: "1"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "Saga"
    description: |-
          The Saga EIP provides a way to define a series of related actions in a Camel route that should be either completed successfully (all of them) or not-executed/compensated. Sagas implementations are able to coordinate distributed services communicating using any transport towards a globally consistent outcome. Although their main purpose is similar, Sagas are different from classical ACID distributed (XA) transactions because the status of the different participating services is guaranteed to be consistent only at the end of the Saga and not in any intermediate step (lack of isolation).
          Conversely, Sagas are suitable for many use cases where usage of 
          distributed transactions is discouraged. For example, services participating in a Saga are allowed to use any kind of datastore: classical databases or even NoSQL non-transactional databases. Sagas are also suitable for being used in stateless cloud services as they do not require a transaction log to be stored alongside the service.
          Differently from transactions, Sagas are also not required to be completed in a small amount of time, because they don’t use database-level locks. They can live for a longer timespan: from few seconds to several days. The Saga EIP implementation based on the MicroProfile sandbox spec (see camel-lra) is indeed called LRA that stands for "Long Running Action". It also supports coordination of external heterogeneous services, written with any language/technology and also running outside a JVM.
          Sagas don’t use locks on data, instead they define the concept of "Compensating Action" that is an action that should be executed when the standard flow encounters an error, with the purpose of restoring the status that was present before the flow execution. Compensating actions can be declared in Camel routes using the Java or XML DSL and will be invoked by Camel only when needed (if the saga is cancelled due to an error).
required:
type: object
properties:
  sagaService:
    title: Saga Service
    description: "Refers to the id to lookup in the registry for the specific CamelSagaService to use."
    type: object
  propagation:
    title: Propagation
    description: "Set the Saga propagation mode (REQUIRED, REQUIRES_NEW, MANDATORY, SUPPORTS, NOT_SUPPORTED, NEVER)."
    example: "REQUIRED"
    type: string
  completionMode:
    title: Completion Mode
    description: "Determine how the saga should be considered complete. When set to AUTO, the saga is completed when the exchange that initiates the saga is processed successfully, or compensated when it completes exceptionally. When set to MANUAL, the user must complete or compensate the saga using the saga:complete or saga:compensate endpoints."
    example: "AUTO"
    type: string
  timeout:
    title: Timeout
    description: "Set the maximum amount of time for the Saga. After the timeout is expired, the saga will be compensated automatically (unless a different decision has been taken in the meantime)."
    type: string
  compensation:
    title: Compensation
    description: "The compensation endpoint URI that must be called to compensate all changes done in the route. The route corresponding to the compensation URI must perform compensation and complete without error. If errors occur during compensation, the saga service may call again the compensation URI to retry."
    type: object
  completion:
    title: Completion
    description: "The completion endpoint URI that will be called when the Saga is completed successfully. The route corresponding to the completion URI must perform completion tasks and terminate without error. If errors occur during completion, the saga service may call again the completion URI to retry."
    type: object
  option:
    title: Option
    description: "Allows to save properties of the current exchange in order to re-use them in a compensation/completion callback route. Options are usually helpful e.g. to store and retrieve identifiers of objects that should be deleted in compensating actions. Option values will be transformed into input headers of the compensation/completion exchange."
    type: object
  description:
    title: Description
    description: "Sets the description of this node."
    type: object
