apiVersion: camel.apache.org/v1alpha1
kind: EIP
metadata:
  name: sample
    camel.apache.org/kamelet.icon: "data:image/gif;base64,R0lGODlhVgA2AMQAAP///+fn58z/md/f38b3lLnni7LfhqbPfLi4uJzDdZm/c4yvaZmZmYGhYYCAgHKPVmZ/TFpwQ01gOjpIKzNAJi04IhogExMYDg0QCgYIBQUHBAAAAP4BAgAAAAAAAAAAACH5BAUUABwALAAAAABWADYAAAX/4CaOZGmeaKquLAm8QCvPdH3C8SbsfO//wKBwSCyKBoNArshsOp9BkcPBWEKv2CxPSrVqv+AhtyoKm8/bzZSsQ7u/Y+97/oyX6fimvZ3vC/d+gUCAgoU7hIaCiIl+i4x5jo90kZJvlJVol5hmmptgnZ5aoKFYo2YGExsVCYGmYRQjFwSNal13PhA2ursmFD+UBgrCw8TFxscKFiQFtGtyeQsaIg+ttWyFCRsNitbPeQYbCtzOt37g4tXkfObh47brfefu130JEBARGxL3rJDd5XQKZCiRgZk/dYHykYjQ7F0ggSMKNqTnR+EGhhO9BRwoMSPAPPkweoSXpwAGgyMNXh0o5IqUk5YumcCMSWQmzT//SN4slXNnmD28ggqVoW6o0aMlnL0YMKWp06dQo0qdSrWqVadVll7dyrWrV6hZAQRgQLas2bNo06pdy7at27IIcMidS7eu3bt48+p9EQIAOw=="
    camel.apache.org/provider: "Kaoto Bridge"
    camel.apache.org/kamelet.group: "Knative"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "Sample"
    description: "The Sample EIP works similar to a wire tap, but instead of tapping every message, the sampling will select a single message in a given time period. This selected message is allowed to pass through, and all other messages are stopped."
    required:
    properties:
      samplePeriod:
        title: Sample Period
        description: "Sets the sample period during which only a single Exchange will pass through."
        type: string
        example: 1000
      messageFrequency:
        title: Message Frequency
        description: "Sets the sample message count which only a single Exchange will pass through after this many received."
        type: numeric
      description:
        title: Description
        description: "Sets the description of this node."
        type: object
