apiVersion: camel.apache.org/v1alpha1
kind: EIP
metadata:
  name: throttle
  annotations:
    camel.apache.org/kamelet.icon: "data:image/gif;base64,R0lGODlhUgAxAHcAMSH+GlNvZnR3YXJlOiBNaWNyb3NvZnQgT2ZmaWNlACH5BAEAAAAALAAAAABQAC8AggAAAAAAAICAgMz/mf///wECAwECAwECAwP/SLrc/jDKSau9OGsYuv9gKI5k+W2Kqa4siRLdIM90bd94rndvrP/AIK4jEGx8wqRyGCgeA8uodEA0apDT7K/61Hp3TWsG+y3LuFeoeU0Nd9lm9FgN/8ox5Pr0fsnro3wWfn9KgRU+AoRShhSIRYqFbmkyRZVAdHY3jBOOlY9MmFlQoW1OkwOeqTYghaszoZsSnamWZyFJHq81mHe0vr/ARS0smq+SCsHJwbasQh9nuzSxEbO0u8+4sLrSx3hqv6Blo6vdfd+qO2ukpWLelLWQl+WC5/HZpnP2gPOH6/pg+Nz9u9fO3ECCbw7KC2hQ4cKC9Bw+TCiRCcOIFXNM4+AvKyM7ih65XewXUhO/Rh0zbnwwrKXLESNRvpzpMqYFZThz6vT0gsDOn0B9JQAAOw=="
    camel.apache.org/provider: "Kaoto Bridge"
    camel.apache.org/kamelet.group: "Knative"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "Throttle"
    description: "Use a Throttler that controls the rate how many or fast messages are flowing to the endpoint."
    required:
    properties:
      expression:
        title: "Expression"
        description: "Expression to configure the maximum number of messages to throttle per request."
        type: object
      correlationExpression:
        title: "Correlation Expression"
        description: "The expression used to calculate the correlation key to use for throttle grouping. The Exchange which has the same correlation key is throttled together."
        type: object
      executorService:
        title: "Executor Service"
        description: "To use a custom thread pool (ScheduledExecutorService) by the throttle."
        type: object
      timePeriodMillis:
        title: "Time Period Millis"
        description: "Sets the time period during which the maximum request count is valid for."
        type: integer
      asyncDelayed:
        title: "Async Delayed"
        description: "Enables asynchronous delay which means the thread will not block while delaying."
        type: boolean
        default: false
      callerRunsWhenRejected:
        title: "Caller Runs When Rejected"
        description: "Whether or not the caller should run the task when it was rejected by the thread pool. Is by default true"
        type: boolean
        default: true
      rejectExecution:
        title: "Reject Execution"
        description: "Whether or not throttler throws the ThrottlerRejectedExecutionException when the exchange exceeds the request limit Is by default false."
        type: boolean
        default: false
      description:
        title: "Description"
        description: "Description of the node"
        type: object
